version: '3.4'

volumes:
  data:
services:
  server:
    image: server
    volumes:
      - /server/node_modules
      - ./server:/usr/src/app
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://docker:mongopw@mongodb:27017
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229
    command: nodemon --exec 'node --inspect=0.0.0.0:9229 .'
  client:
    image: client
    volumes:
      - /client/node_modules
      - ./client:/usr/src/app
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      NPM_CONFIG_UNSAFE_PERM: true
    ports:
      - 8080:8080
      # - 9228:9228
    # command: node --experimental-loader=@vavite/node-loader
    depends_on:
      - server
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  database:
    image: mongo